import 'package:flutter/material.dart';

class UIColor {
  static const Color white = Color(0xFFFFFFFF);
  static const Color primary = Color(0xFF6772F1);
  static const Color text_secondary = Color(0xFFC8C8C8);
  static const Color disable_bg = Color(0xFFD7D7D7);
  static const Color accent = Color(0xFFF38847);
  static const Color accent2 = Color(0xFF1AAB4B);
  static const Color waring_color = Color(0xFFFFD54F);
  static const Color text_body = Color(0xFF5F5F5F);
  static const Color danger = Color(0xFFE34747);
  static const Color holder = Color(0xFFEDF1F5);
  static const Color text_header = Color(0xDE000000);
  static const Color silver_sand = Color(0xFFC4C4C4);
  static const Color blue_yonder = Color(0xFF4267B2);
  static const Color cinnabar = Color(0xFFDB4437);
  static const Color antique_white = Color(0xFFFAEBD5);
  static const Color alice_blue = Color(0xFFEDF1F5);
  static const Color black = Color(0xFF000000);
  static const Color eclipse = Color(0xFF3A3A3A);
  static const Color pink_swan27 = Color(0x40B7B7B7);
  static const Color box_shadow_color = Color(0x40737373);
  static const Color adoption_color = Color(0xff127189);
  static const Color adoption_color_bg = Color(0xffEFF8FB);
  static const Color mating_color = Color(0xffE09BAD);
  static const Color mating_color_bg = Color(0xfFFFF2F8);
  static const Color lose_color_bg = Color(0xffF6F6F6);
  static const Color pattens_blue = Color(0xFFD8ECF1);
  static const Color lavender_blush = Color(0xFFF8EAF0);
  static const Color white_smoke = Color(0xFFF3F3F3);
  static const Color alice_blue2 = Color(0xFFEFF8FB);
  static const Color viking = Color(0xFF60B9CF);
  static const Color kobi = Color(0xFFE09BAD);
  static const Color white_smoke2 = Color(0xFFF6F6F6);
  static const Color allports = Color(0xFF127189);
  static const Color charm = Color(0xFFD67D94);
  static const Color persian_red = Color(0xFFD14242);
  static const Color dodger_blue = Color(0xFF2196F3);
  static const Color pattens_blue2 = Color(0xFFD2E8F9);
  static const Color whisper = Color(0xFFE8E8E8);
  static const Color alice_blue3 = Color(0xFFF5FAFF);
}
