name: meowoof
description: Social network for pet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  retrofit: ^2.0.0-beta1

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^4.1.1

  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.0.1

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App"
  get_it: ^6.1.1

  # Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
  injectable: ^1.3.0

  # Suga Core Package.
  suga_core: ^1.0.0

  # Open screens/snackbars/dialogs without context, manage states and inject dependencies easily with GetX.
  get: ^4.1.4

  # Easy and Fast internationalizing and localization your Flutter Apps, this package simplify the internationalizing process.
  easy_localization: ^3.0.0

  # A simple Event Bus using Dart Streams for decoupling applications
  event_bus: ^2.0.0

  #A flutter plugin for adapting screen and font size.Let your UI display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Email validate
  email_validator: ^2.0.1

  # The hasura_connect is designed to facilitate Hasura's integration with Flutter applications, leveraging the full power of Graphql.
  hasura_connect: ^3.0.2

  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps.
  firebase_core: ^1.1.1

  # A Flutter plugin to use the Firebase Authentication API.
  firebase_auth: ^1.1.4

  # A Flutter plugin for Google Sign In.
  google_sign_in: ^5.0.3

  # A Flutter plugin for using the native Facebook Login SDKs on Android and iOS.
  flutter_facebook_auth: ^3.3.3+1

  # Toast Library for Flutter
  fluttertoast: ^8.0.6

  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.7.5

  #  Easily use any of the 977 fonts (and their variants) from fonts.google.com in your Flutter app.
  google_fonts: ^2.0.0

  # A library useful for creating fuzzy timestamps. (e.g. "5 minutes ago")
  timeago: ^3.0.2
  # A Flutter plugin for iOS, Android and Web for playing back video on a Widget surface.
  better_player: ^0.0.66
  # Create awesome and powerful modal bottom sheets.
  modal_bottom_sheet: ^2.0.0
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^2.0.0
  # A package provides lazily load and display small chunks of items as the user scrolls down the screen
  infinite_scroll_pagination: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # An opiniated, community-driven set of lint rules for Dart and Flutter projects. Like pedantic but stricter
  lint: ^1.5.3
  # A build system for Dart code generation and modular compilation.
  build_runner: ^1.12.2

  # Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
  injectable_generator: ^1.2.2

  # retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  retrofit_generator: ^2.0.0-beta3

  # The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
  flutter_gen_runner: ^3.1.1

flutter_gen:
  output: lib/
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - resources/langs/
    - resources/icons/
    - resources/google_fonts/
